name: Deploy to Hostinger (FTPS)

on:
  push:
    branches: [ "main" ]   # deploy em todo push na main
  workflow_dispatch:        # permite rodar manualmente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Add .htaccess for SPA (React Router)
        run: |
          cat > dist/.htaccess <<'EOF'
          RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]
          EOF

      - name: Deploy via FTPS to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftps
          local-dir: dist
          server-dir: ${{ secrets.FTP_DIR }}
          dangerous-clean-slate: true   # limpa a pasta remota antes de enviar
